name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Upload to GitHub Release
      run: |
        cp two-factor-endpoint/build/libs/two-factor-endpoint-latest.jar two-factor-endpoint-${{ env.VERSION }}.jar
        gh release upload ${{ env.VERSION }} two-factor-endpoint-${{ env.VERSION }}.jar
      env:
        VERSION: ${{ github.ref_name }}
        
